apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberlearn-frontend
  labels:
    app: cyberlearn-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberlearn-frontend
  template:
    metadata:
      labels:
        app: cyberlearn-frontend
    spec:
      containers:
        - name: frontend
          image: cyberlearn/frontend:local
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cyberlearn-frontend
spec:
  selector:
    app: cyberlearn-frontend
  ports:
    - port: 80
      targetPort: 3000
